#!/bin/bash

source venv/bin/activate
venv/bin/python3 -m pip install --upgrade twine
venv/bin/python3 -m pip install --upgrade setuptools wheel
venv/bin/python3 setup.py sdist bdist_wheel
#venv/bin/python3 -m twine upload
rm -rf dist/
rm -rf tekek.egg-info/
deactivate